### PR TITLE
update instances to ignore changes to host attach script

### PR DESCRIPTION
**Pull request by bhpratt**
### Description

By default, if the host_attach script changes, terraform resources will recognize those changes and trigger a replace. This is a problem for satellite hosts because we do not want changes to the attach script (such as a new host_queue_token) to cause a replace. This should only impact existing nodes. Adding ignore changes stanzas to address this.

reference: https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes

docs showing these fields causes new hosts or in the case of aws, host will stop/start:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#custom_data
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#user_data_base64
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#metadata_startup_script

### Types of changes in this PR

adding ignore_changes blocks to instance resources.

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.

---

### Checklist for reviewers

- [ ] The PR references a GitHub issue.
- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

### CODE REVIEW

**Comment by bhpratt** [comment]
Complicating factor - modules cannot have lifecycle blocks: https://github.com/hashicorp/terraform/issues/27360

**Comment by finken2** [comment]
For AWS, looks like newer module versions have a property that defaults to working how we want, `user_data_replace_on_change`. we'll do some testing and bump the module version on a different PR.
For GCP, there's some another property startup_script instead of the metadata we're using. Might be interesting to see how that behaves. Additionally, we have another issue on gcp in this same area where our script runs on every boot, so maybe look at both of these together.

**Comment by dbellagio** [comment]
In my fork, I refactored the GCP code to use resources instead of modules and then I can use Terraform lifecycle to ignore changes to the startup script.   I am not sure about the issue of the script running every time after reboot.   What problem does the "run every-time after reboot" cause?

**Comment by finken2** [comment]
yeah, i was considering that refactor as well. Will have to see what it looks like. 
The run every time doesn't really cause an issue, it's just wrong. If we don't change it at the terraform level, we should at the least modify the script so that it kicks out quickly if the  ibm-host-attach.service is already up and running.

**Review by finken2 — APPROVED** [review]

**Comment by dbellagio** [comment]
@finken2 I have a working session with the customer (on 3/15) to test out the refactored code.  I'll keep adding to my fork and cleanup stuff as needed based on the testing we do.

**Pull request merged**
